//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
